name: MQtests 

on: [push, pull_request]

jobs:
  test:
    name: FirstTest
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        uses: actions/checkout@v1
        with:
          rabbitmq version: '3.8.2-management-alpine'
          host port: 5672
          rabbitmq user: 'ala'
          rabbitmq password: 'ala'
        run: |
          - rabbitmqctl status
          - rabbitmq-plugins enable rabbitmq_stomp
          - export PYTHONPATH=${PWD%/*}
          - pytest Resources/MessageQueue/test/Test_MQCommunication.py
